//////////////////////////////////////////////////////////////////////////////
// This file is part of the Maple Engine                              		//
//////////////////////////////////////////////////////////////////////////////
#version 450

#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : require

#define DEPTHPROBE_UPDATE

#include "DDGICommon.glsl"
#include "ProbeUpdate.glsl"